up

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1,12 +1,12 @@
 #!/bin/bash
 #====================================================
-#	SCRIPT: CONEXAO VSAIOSSH MANAGER
-#	DESENVOLVIDO POR:	VSAIOSSH
+#	SCRIPT: CONEXAO SSHPLUS MANAGER
+#	DESENVOLVIDO POR:	CRAZY_VPN
 #	DATA ATUALIZACAO:	28-04-2021 
-#	CONTATO TELEGRAM:	http://t.me/vsaiossh 
-#	CANAL TELEGRAM:	http://t.me/vsaiossh 
+#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
+#	CANAL TELEGRAM:	http://t.me/sshplus
 #====================================================
-[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@VSAIOSSH" ]] && {
+[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@CRAZY_VPN" ]] && {
 	ram1=$(free -h | grep -i mem | awk {'print $2'})
 	ram2=$(free -h | grep -i mem | awk {'print $4'})
 	ram3=$(free -h | grep -i mem | awk {'print $3'})
@@ -318,117 +318,149 @@
 	}
 
 	fun_drop() {
-    if pgrep dropbear 1>/dev/null 2>/dev/null; then
-        clear
-        dpbr=$(ss -tulnp | grep dropbear | awk '{print $5}' | cut -d: -f2 | xargs)
-        [[ -z "$dpbr" ]] && dpbr="\033[1;31mINDISPONIVEL"
-
-        if pgrep limiter 1>/dev/null 2>/dev/null; then
-            stats='\033[1;32m◉ '
-        else
-            stats='\033[1;31m○ '
-        fi
-
-        echo -e "\E[44;1;37m              GERENCIAR DROPBEAR               \E[0m"
-        echo -e "\n\033[1;33mPORTAS\033[1;37m: \033[1;32m$dpbr"
-        echo ""
-        echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mLIMITER DROPBEAR $stats\033[0m"
-        echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mALTERAR PORTA DROPBEAR\033[0m"
-        echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mREMOVER DROPBEAR\033[0m"
-        echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
-        echo ""
-        echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "
-        read resposta
-
-        case "$resposta" in
-            1)
-                if pgrep limiter 1>/dev/null 2>/dev/null; then
-                    echo -e "\033[1;32mParando o limiter... \033[0m"
-                    pkill limiter
-                    echo -e "\n\033[1;31m LIMITER DESATIVADO \033[0m"
-                else
-                    echo -e "\n\033[1;32mIniciando o limiter... \033[0m"
-                    screen -d -m -t limiter droplimiter
-                    echo -e "\n\033[1;32m  LIMITER ATIVADO \033[0m"
-                fi
-                sleep 3
-                fun_drop
-                ;;
-            2)
-                echo ""
-                echo -ne "\033[1;32mQUAL PORTA DESEJA UTILIZAR \033[1;33m?\033[1;37m "
-                read pt
-                sed -i "s/^DROPBEAR_PORT=.*/DROPBEAR_PORT=$pt/g" /etc/default/dropbear
-                echo -e "\n\033[1;32mREINICIANDO DROPBEAR!\033[0m"
-                systemctl restart dropbear
-                echo -e "\n\033[1;32mPORTA ALTERADA COM SUCESSO!\033[0m"
-                sleep 3
-                fun_conexao
-                ;;
-            3)
-                echo -e "\n\033[1;32mREMOVENDO O DROPBEAR !\033[0m"
-                systemctl stop dropbear
-                apt remove dropbear dropbear-bin dropbear-run -y
-                apt purge dropbear -y
-                rm -rf /etc/default/dropbear
-                apt autoremove -y
-                echo -e "\n\033[1;32mDROPBEAR REMOVIDO COM SUCESSO !\033[0m"
-                sleep 3
-                fun_conexao
-                ;;
-            0)
-                echo -e "\n\033[1;31mRetornando...\033[0m"
-                sleep 2
-                fun_conexao
-                ;;
-            *)
-                echo -e "\n\033[1;31mOpção inválida...\033[0m"
-                sleep 2
-                fun_conexao
-                ;;
-        esac
-    else
-        clear
-        echo -e "\E[44;1;37m           INSTALADOR DROPBEAR              \E[0m"
-        echo -e "\n\033[1;33mVOCÊ ESTÁ PRESTES A INSTALAR O DROPBEAR !\033[0m\n"
-        echo -ne "\033[1;32mDESEJA CONTINUAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
-        read resposta
-        [[ "$resposta" = 's' ]] && {
-            echo -e "\n\033[1;33mDEFINA UMA PORTA PARA O DROPBEAR !\033[0m\n"
-            echo -ne "\033[1;32mQUAL A PORTA \033[1;33m?\033[1;37m "
-            read porta
-            [[ -z "$porta" ]] && {
-                echo -e "\n\033[1;31mPorta inválida!"
-                sleep 3
-                fun_conexao
-            }
-            echo -e "\n\033[1;32mINSTALANDO O DROPBEAR ! \033[0m"
-            apt-get update -y
-            apt-get install dropbear -y
-
-            echo -e "\033[1;32mCONFIGURANDO PORTA DROPBEAR !\033[0m"
-            sed -i 's/^NO_START=1/NO_START=0/g' /etc/default/dropbear
-            sed -i "s/^DROPBEAR_PORT=.*/DROPBEAR_PORT=$porta/g" /etc/default/dropbear
-            sed -i 's/^DROPBEAR_EXTRA_ARGS=.*/DROPBEAR_EXTRA_ARGS="-p 110"/g' /etc/default/dropbear
-
-            echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
-            echo "PermitTunnel yes" >> /etc/ssh/sshd_config
-
-            echo -e "\033[1;32mFINALIZANDO INSTALAÇÃO !\033[0m"
-            systemctl restart ssh
-            systemctl start dropbear
-
-            echo -e "\n\033[1;32mINSTALAÇÃO CONCLUÍDA \033[1;33mPORTA: \033[1;37m$porta\033[0m"
-            [[ $(grep -c "/bin/false" /etc/shells) = '0' ]] && echo "/bin/false" >> /etc/shells
-            sleep 2
-            fun_conexao
-        } || {
-            echo -e "\n\033[1;31mRetornando...\033[0m"
-            sleep 3
-            fun_conexao
-        }
-    fi
-}
+		if netstat -nltp | grep 'dropbear' 1>/dev/null 2>/dev/null; then
+			clear
+			[[ $(netstat -nltp | grep -c 'dropbear') != '0' ]] && dpbr=$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs) || sqdp="\033[1;31mINDISPONIVEL"
+			if ps x | grep "limiter" | grep -v grep 1>/dev/null 2>/dev/null; then
+				stats='\033[1;32m◉ '
+			else
+				stats='\033[1;31m○ '
+			fi
+			echo -e "\E[44;1;37m              GERENCIAR DROPBEAR               \E[0m"
+			echo -e "\n\033[1;33mPORTAS\033[1;37m: \033[1;32m$dpbr"
+			echo ""
+			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mLIMITER DROPBEAR $stats\033[0m"
+			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mALTERAR PORTA DROPBEAR\033[0m"
+			echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mREMOVER DROPBEAR\033[0m"
+			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
+			echo ""
+			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+			read resposta
+			if [[ "$resposta" = '1' ]]; then
+				clear
+				if ps x | grep "limiter" | grep -v grep 1>/dev/null 2>/dev/null; then
+					echo -e "\033[1;32mParando o limiter... \033[0m"
+					echo ""
+					fun_stplimiter() {
+						pidlimiter=$(ps x | grep "limiter" | awk -F "pts" {'print $1'})
+						kill -9 $pidlimiter
+						screen -wipe
+					}
+					fun_bar 'fun_stplimiter' 'sleep 2'
+					echo -e "\n\033[1;31m LIMITER DESATIVADO \033[0m"
+					sleep 3
+					fun_drop
+				else
+					echo -e "\n\033[1;32mIniciando o limiter... \033[0m"
+					echo ""
+					fun_bar 'screen -d -m -t limiter droplimiter' 'sleep 3'
+					echo -e "\n\033[1;32m  LIMITER ATIVADO \033[0m"
+					sleep 3
+					fun_drop
+				fi
+			elif [[ "$resposta" = '2' ]]; then
+				echo ""
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m "
+				read pt
+				echo ""
+				verif_ptrs $pt
+				var1=$(grep 'DROPBEAR_PORT=' /etc/default/dropbear | cut -d'=' -f2)
+				echo -e "\033[1;32mALTERANDO PORTA DROPBEAR!"
+				sed -i "s/\b$var1\b/$pt/g" /etc/default/dropbear >/dev/null 2>&1
+				echo ""
+				fun_bar 'sleep 2'
+				echo -e "\n\033[1;32mREINICIANDO DROPBEAR!"
+				echo ""
+				fun_bar 'service dropbear restart' '/etc/init.d/dropbear restart'
+				echo -e "\n\033[1;32mPORTA ALTERADA COM SUCESSO!"
+				sleep 3
+				clear
+				fun_conexao
+			elif [[ "$resposta" = '3' ]]; then
+				echo -e "\n\033[1;32mREMOVENDO O DROPBEAR !\033[0m"
+				echo ""
+				fun_dropunistall() {
+					service dropbear stop && /etc/init.d/dropbear stop
+					apt remove dropbear-run -y
+					apt remove dropbear -y
+					apt purge dropbear -y
+					rm -rf /etc/default/dropbear
+                    apt autoremove -y
+				}
+				fun_bar 'fun_dropunistall'
+				echo -e "\n\033[1;32mDROPBEAR REMOVIDO COM SUCESSO !\033[0m"
+				sleep 3
+				clear
+				fun_conexao
+			elif [[ "$resposta" = '0' ]]; then
+				echo -e "\n\033[1;31mRetornando...\033[0m"
+				sleep 2
+				fun_conexao
+			else
+				echo -e "\n\033[1;31mOpcao invalida...\033[0m"
+				sleep 2
+				fun_conexao
+			fi
+		else
+			clear
+			echo -e "\E[44;1;37m           INSTALADOR DROPBEAR              \E[0m"
+			echo -e "\n\033[1;33mVC ESTA PRESTES A INSTALAR O DROPBEAR !\033[0m\n"
+			echo -ne "\033[1;32mDESEJA CONTINUAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+			read resposta
+			[[ "$resposta" = 's' ]] && {
+				echo -e "\n\033[1;33mDEFINA UMA PORTA PARA O DROPBEAR !\033[0m\n"
+				echo -ne "\033[1;32mQUAL A PORTA \033[1;33m?\033[1;37m "
+				read porta
+				[[ -z "$porta" ]] && {
+					echo -e "\n\033[1;31mPorta invalida!"
+					sleep 3
+					clear
+					fun_conexao
+				}
+				verif_ptrs $porta
+				echo -e "\n\033[1;32mINSTALANDO O DROPBEAR ! \033[0m"
+				echo ""
+				fun_instdrop() {
+					apt-get update -y
+					apt-get install dropbear -y
+				}
+				fun_bar 'fun_instdrop'
+				fun_ports() {
+					sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear >/dev/null 2>&1
+					sed -i "s/DROPBEAR_PORT=22/DROPBEAR_PORT=$porta/g" /etc/default/dropbear >/dev/null 2>&1
+					sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 110"/g' /etc/default/dropbear >/dev/null 2>&1
+				}
+				echo ""
+				echo -e "\033[1;32mCONFIGURANDO PORTA DROPBEAR !\033[0m"
+				echo ""
+				fun_bar 'fun_ports'
+				grep -v "^PasswordAuthentication yes" /etc/ssh/sshd_config >/tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
+				echo "PasswordAuthentication yes" >>/etc/ssh/sshd_config
+				grep -v "^PermitTunnel yes" /etc/ssh/sshd_config >/tmp/ssh && mv /tmp/ssh /etc/ssh/sshd_config
+				echo "PermitTunnel yes" >>/etc/ssh/sshd_config
+				echo ""
+				echo -e "\033[1;32mFINALIZANDO INSTALACAO !\033[0m"
+				echo ""
+				fun_ondrop() {
+				    service ssh restart
+					service dropbear start
+					/etc/init.d/dropbear restart
+				}
+				fun_bar 'fun_ondrop' 'sleep 1'
+				echo -e "\n\033[1;32mINSTALACAO CONCLUIDA \033[1;33mPORTA: \033[1;37m$porta\033[0m"
+				[[ $(grep -c "/bin/false" /etc/shells) = '0' ]] && echo "/bin/false" >>/etc/shells
+				sleep 2
+				clear
+				fun_conexao
+			} || {
+				echo""
+				echo -e "\033[1;31mRetornando...\033[0m"
+				sleep 3
+				clear
+				fun_conexao
+			}
+		fi
+	}
 
 	inst_ssl() {
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
@@ -536,7 +568,7 @@
 					#cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
 					#rm key.pem cert.pem >/dev/null 2>&1
 					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
-					cd /etc/stunnel && wget https://raw.githubusercontent.com/venturesolution/VSAIOMANAGER/master/Install/stunnel.pem && cd $HOME
+					cd /etc/stunnel && wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/stunnel.pem && cd $HOME
 				}
 				fun_bar 'ssl_certif'
 				echo -e "\n\033[1;32mINICIANDO O SSL TUNNEL !\033[0m"
@@ -1042,7 +1074,7 @@
 			fun_dep() {
 				wget -O ~/EasyRSA-3.0.1.tgz "https://github.com/OpenVPN/easy-rsa/releases/download/3.0.1/EasyRSA-3.0.1.tgz"
 				[[ ! -e $HOME/EasyRSA-3.0.1.tgz ]] && {
-					wget -O ~/EasyRSA-3.0.1.tgz "https://raw.githubusercontent.com/venturesolution/VSAIOMANAGER/master/Install/EasyRSA-3.0.1.tgz"
+					wget -O ~/EasyRSA-3.0.1.tgz "https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/EasyRSA-3.0.1.tgz"
 				}
 				tar xzf ~/EasyRSA-3.0.1.tgz -C ~/
 				mv ~/EasyRSA-3.0.1/ /etc/openvpn/
@@ -1292,12 +1324,12 @@ exit 0' >$RCLOCAL
 				verif_ptrs $porta
 				fun_inisocks() {
 					sleep 1
-					screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta
+					screen -dmS proxy python /etc/SSHPlus/proxy.py $porta
 					[[ $(grep -wc "proxy.py" /etc/autostart) = '0' ]] && {
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
 					} || {
 						sed -i '/proxy.py/d' /etc/autostart
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
 					}
 				}
 				echo ""
@@ -1447,7 +1479,7 @@ exit 0' >$RCLOCAL
 				echo ""
 				abrirptsks() {
 					sleep 1
-					screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta
+					screen -dmS proxy python /etc/SSHPlus/proxy.py $porta
 					sleep 1
 				}
 				fun_bar 'abrirptsks'
