000001

diff --git a/Modulos/remover b/Modulos/remover
--- a/Modulos/remover
+++ b/Modulos/remover
@@ -1,4 +1,4 @@
-#!/bin/bash 
+#!/bin/bash
 remove_ovp () {
 if [[ -e /etc/debian_version ]]; then
 	GROUPNAME=nogroup
@@ -18,18 +18,17 @@ chown nobody:$GROUPNAME /etc/openvpn/crl.pem
 } > /dev/null 2>&1
 [[ ! -e /usr/lib/sshplus ]] && rm -rf /bin/ > /dev/null 2>&1
 database="/root/usuarios.db"
-tput reset
-echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
-echo -e "\033[0;34m┃\E[44;1;37m           REMOVER USUARIO SSH           \E[0m\033[0;34m┃"
-echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m\n"
-echo -e "\E[38;5;196m|\E[38;5;33m01\E[38;5;196m|\033[1;37m➜ \E[38;5;15mREMOVER UM USUARIO"
-echo -e "\E[38;5;196m|\E[38;5;33m02\E[38;5;196m|\033[1;37m➜ \E[38;5;15mREMOVER TODOS USUARIOS"
-echo -e "\E[38;5;196m|\E[38;5;33m00\E[38;5;196m|\033[1;37m➜ \E[38;5;15mVOLTAR"
+clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Remover Usuário SSH" ; tput sgr0
 echo ""
-read -p "$(echo -e "\033[1;32mOQUE DESEJA FAZER\033[1;31m ?\033[1;37m : ")" resp
+echo -e "\033[1;31m[\033[1;36m1\033[1;31m]\033[1;33m REMOVER UM USUARIO"
+echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;33m REMOVER TODOS USUARIOS"
+echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;33m VOLTAR"
+echo ""
+read -p "$(echo -e "\033[1;32mOQUE DESEJA FAZER\033[1;31m ?\033[1;37m : ")" -e -i 1 resp
 if [[ "$resp" = "1" ]]; then
-tput reset
-echo -e "\E[44;1;37m           REMOVER USUARIO SSH \E[0m"
+clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Remover Usuário SSH" ; tput sgr0
 echo ""
 echo -e "\033[1;33mLISTA DE USUARIOS: \033[0m"
 echo""
@@ -45,28 +44,20 @@ while read _user; do
 done <<< "${_userT}"
 echo ""
 num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
-echo -ne "\033[1;32mDIGITE OU SELECIONE UM USUARIO \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
+echo -ne "\033[1;32mDigite ou selecione um usuario \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
 user=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
 if [[ -z $option ]]; then
-echo""
-echo -e "\E[44;1;196m USUARIO VAZIO OU INVÁLIDO! \E[0m  "
-echo""
-	echo -e "\033[1;31mRETORNANDO...\033[0m"
-	sleep 1.5s
-	remover
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "  Usuario vazio ou inválido!   " ; echo "" ; tput sgr0
+	exit 1
 elif [[ -z $user ]]; then
-echo""
-echo -e "\E[44;1;196m USUARIO VAZIO OU INVÁLIDO! \E[0m  "
-echo""
-	echo -e "\033[1;31mRETORNANDO...\033[0m"
-	sleep 1.5s
-	remover
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo " Usuário vazio ou inválido! " ; echo "" ; tput sgr0
+	exit 1
 else
 	if cat /etc/passwd |grep -w $user > /dev/null; then
 		echo ""
-		pkill -f "$user" > /dev/null 2>/dev/null
-		userdel --force $user > /dev/null 2>/dev/null
-		echo -e "\E[41;1;37m USUARIO $user REMOVIDO COM SUCESSO! \E[0m"
+		pkill -f "$user" > /dev/null 2>&1
+		deluser --force $user > /dev/null 2>&1
+		echo -e "\E[41;1;37m Usuario $user removido com sucesso! \E[0m"
 		grep -v ^$user[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
 		rm /etc/SSHPlus/senha/$user 1>/dev/null 2>/dev/null
 		if [[ -e /etc/openvpn/server.conf ]]; then
@@ -76,24 +67,21 @@ else
 	elif [[ "$(cat "$database"| grep -w $user| wc -l)" -ne "0" ]]; then
 		ps x | grep $user | grep -v grep | grep -v pt > /tmp/rem
 		if [[ `grep -c $user /tmp/rem` -eq 0 ]]; then
-			pkill -f "$user" > /dev/null 2>/dev/null
-			userdel --force $user > /dev/null 2>/dev/null
+			deluser --force $user > /dev/null 2>&1
 			echo ""
-			echo -e "\E[41;1;37m USUARIO $user REMOVIDO COM SUCESSO! \E[0m"
+			echo -e "\E[41;1;37m Usuario $user removido com sucesso! \E[0m"
 			grep -v ^$user[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
 			rm /etc/SSHPlus/senha/$user 1>/dev/null 2>/dev/null
 			if [[ -e /etc/openvpn/server.conf ]]; then
 				remove_ovp $user
 		    fi
-	echo -e "\n\033[1;31mRETORNANDO...\033[0m"
-	sleep 1.5s
-	remover
+			exit 1
 		else
 		    echo ""
-			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "USUÁRIO CONECTADO. DESCONECTANDO..." ; tput sgr0
+			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Usuário conectado. Desconectando..." ; tput sgr0
 			pkill -f "$user" > /dev/null 2>&1
 			deluser --force $user > /dev/null 2>&1
-			echo -e "\E[41;1;37m USUARIO $user REMOVIDO COM SUCESSO! \E[0m"
+			echo -e "\E[41;1;37m Usuario $user removido com sucesso! \E[0m"
 			grep -v ^$user[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
 			rm /etc/SSHPlus/senha/$user 1>/dev/null 2>/dev/null
 			if [[ -e /etc/openvpn/server.conf ]]; then
@@ -102,25 +90,19 @@ else
 			exit 1
 		fi
 	else
-		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "O USUÁRIO $user NÃO EXISTE!" ; echo "" ; tput sgr0
+		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "O usuário $user não existe!" ; echo "" ; tput sgr0
 	fi
 fi
 elif [[ "$resp" = "2" ]]; then
-	tput reset
-echo -e "\E[44;1;37mREMOVER USUARIO SSH  \E[0m"
+	clear
+	tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Remover Usuário SSH" ; tput sgr0
 	echo ""
 	echo -ne "\033[1;33mREALMENTE DESEJA REMOVER TODOS USUARIOS \033[1;37m[s/n]: "; read opc	
-	if [[ "$opc" = "n" ]]; then	
-	echo -e "\n\033[1;31mRETORNANDO...\033[0m"
-	sleep 1.5s
-	tput reset
-	remover
-	fi
 	if [[ "$opc" = "s" ]]; then
-	echo -e "\n\033[1;33mAGUARDE\033[1;32m.\033[1;31m.\033[1;33m.\033[0m"
+	echo -e "\n\033[1;33mAguarde\033[1;32m.\033[1;31m.\033[1;33m.\033[0m"
 		for user in $(cat /etc/passwd |awk -F : '$3 > 900 {print $1}' |grep -vi "nobody"); do
-		pkill -f "$user" > /dev/null 2>/dev/null
-		userdel --force $user > /dev/null 2>/dev/null
+			pkill -f $user > /dev/null 2>&1
+			deluser --force $user > /dev/null 2>&1
         if [[ -e /etc/openvpn/server.conf ]]; then
 		   remove_ovp $user
 		fi
@@ -128,25 +110,17 @@ echo -e "\E[44;1;37mREMOVER USUARIO SSH  \E[0m"
 		rm $HOME/usuarios.db && touch $HOME/usuarios.db
         rm *.zip > /dev/null 2>&1
 		echo -e "\n\033[1;32mUSUARIOS REMOVIDOS COM SUCESSO!\033[0m"
-		echo -e "\n\033[1;31mRETORNANDO...\033[0m"
-		sleep 1.5s
-				else
-			echo ""
-			echo -e "\033[1;31mOpcao invalida !\033[0m"
-			sleep 1
-remover
-fi
+		sleep 2
+		menu
+	else
+		echo -e "\n\033[1;31mRetornando ao menu...\033[0m"
+		sleep 2
+		menu
 	fi
-        elif [[ "$resposta" = '0' ]]; then
-			echo ""
-			echo -e "\033[1;31mRetornando...\033[0m"
-			sleep 1
-			menu
-		else
-			echo ""
-			echo -e "\033[1;31mOpcao invalida !\033[0m"
-			sleep 1
-remover
+elif [[ "$resp" = "3" ]]; then
+	menu
+else
+	echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+	sleep 1.5s
+	menu
 fi
-}
-remover
